// Mocks generated by Mockito 5.0.8 from annotations
// in submission_one_menjadi_flutter_developer_expert_ditonton_app/test/presentation/provider/tv_show_list_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/common/failure_equatable.dart' as _i6;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/entities/tv_entities.dart' as _i7;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/repositories/tv_show_repo.dart' as _i2;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/tv/get_all_now_playing_tv_show.dart' as _i4;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/tv/get_all_popular_tv_show.dart' as _i8;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/tv/get_all_top_rated_tv_show.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeTVShowRepository extends _i1.Fake implements _i2.TVShowRepo {}

class _FakeEither<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetNowPlayingTV].
///
/// See the documentation for Mockito's code generation for more information.
class GetNowPlayingTVShowMock extends _i1.Mock
    implements _i4.GetAllNowPlayingTVShow {
  GetNowPlayingTVShowMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepo get tvShowRepo =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository()) as _i2.TVShowRepo);
  @override
  _i5.Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>>.value(
              _FakeEither<_i6.FailureEquitable, List<_i7.TVEntities>>())) as _i5
          .Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>>);
}

/// A class which mocks [GetPopularTV].
///
/// See the documentation for Mockito's code generation for more information.
class GetPopularTVShowMock extends _i1.Mock implements _i8.GetAllPopularTVShow {
  GetPopularTVShowMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepo get tvShowRepo =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository()) as _i2.TVShowRepo);
  @override
  _i5.Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>>.value(
              _FakeEither<_i6.FailureEquitable, List<_i7.TVEntities>>())) as _i5
          .Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>>);
}

/// A class which mocks [GetTopRatedTV].
///
/// See the documentation for Mockito's code generation for more information.
class GetTopRatedTVShowMock extends _i1.Mock implements _i9.GetTopRatedTV {
  GetTopRatedTVShowMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepo get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository()) as _i2.TVShowRepo);
  @override
  _i5.Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>> execute() =>
      (super.noSuchMethod(Invocation.method(#execute, []),
          returnValue: Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>>.value(
              _FakeEither<_i6.FailureEquitable, List<_i7.TVEntities>>())) as _i5
          .Future<_i3.Either<_i6.FailureEquitable, List<_i7.TVEntities>>>);
}
