// Mocks generated by Mockito 5.3.2 from annotations
// in submission_one_menjadi_flutter_developer_expert_ditonton_app/test/presentation/provider/movie_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/common/failure_equatable.dart'
    as _i6;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/entities/movie_detail.dart'
    as _i7;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/entities/movie_entities.dart'
    as _i9;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/repositories/movie_repo.dart'
    as _i2;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/get_all_movie_detail.dart'
    as _i4;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/get_all_movie_recommendations.dart'
    as _i8;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/get_all_watchlist_status.dart'
    as _i10;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/remove_all_watchlist.dart'
    as _i12;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/save_all_watchlist.dart'
    as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMovieRepository_0 extends _i1.SmartFake
    implements _i2.MovieRepository {
  _FakeMovieRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetAllMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllMovieDetail extends _i1.Mock implements _i4.GetAllMovieDetail {
  MockGetAllMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movierepository => (super.noSuchMethod(
        Invocation.getter(#movierepository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#movierepository),
        ),
      ) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i6.FailureEquitable, _i7.MovieDetail>> execute(
          int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.FailureEquitable, _i7.MovieDetail>>.value(
                _FakeEither_1<_i6.FailureEquitable, _i7.MovieDetail>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.FailureEquitable, _i7.MovieDetail>>);
}

/// A class which mocks [GetAllMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllMovieRecommendations extends _i1.Mock
    implements _i8.GetAllMovieRecommendations {
  MockGetAllMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movierepository => (super.noSuchMethod(
        Invocation.getter(#movierepository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#movierepository),
        ),
      ) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i6.FailureEquitable, List<_i9.Movie>>> execute(
          dynamic id) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.FailureEquitable, List<_i9.Movie>>>.value(
                _FakeEither_1<_i6.FailureEquitable, List<_i9.Movie>>(
          this,
          Invocation.method(
            #execute,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.FailureEquitable, List<_i9.Movie>>>);
}

/// A class which mocks [GetAllWatchListTheMoviesStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllWatchListTheMoviesStatus extends _i1.Mock
    implements _i10.GetAllWatchListTheMoviesStatus {
  MockGetAllWatchListTheMoviesStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository => (super.noSuchMethod(
        Invocation.getter(#movieRepository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#movieRepository),
        ),
      ) as _i2.MovieRepository);
  @override
  _i5.Future<bool> execute(int? id) => (super.noSuchMethod(
        Invocation.method(
          #execute,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [SaveAllWatchListTheMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveAllWatchListTheMovies extends _i1.Mock
    implements _i11.SaveAllWatchListTheMovies {
  MockSaveAllWatchListTheMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movierepository => (super.noSuchMethod(
        Invocation.getter(#movierepository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#movierepository),
        ),
      ) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i6.FailureEquitable, String>> execute(
          _i7.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [movie],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.FailureEquitable, String>>.value(
            _FakeEither_1<_i6.FailureEquitable, String>(
          this,
          Invocation.method(
            #execute,
            [movie],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.FailureEquitable, String>>);
}

/// A class which mocks [RemoveAllWatchlistTheMovies].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveAllWatchlistTheMovies extends _i1.Mock
    implements _i12.RemoveAllWatchlistTheMovies {
  MockRemoveAllWatchlistTheMovies() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MovieRepository get movieRepository => (super.noSuchMethod(
        Invocation.getter(#movieRepository),
        returnValue: _FakeMovieRepository_0(
          this,
          Invocation.getter(#movieRepository),
        ),
      ) as _i2.MovieRepository);
  @override
  _i5.Future<_i3.Either<_i6.FailureEquitable, String>> execute(
          _i7.MovieDetail? movie) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [movie],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.FailureEquitable, String>>.value(
            _FakeEither_1<_i6.FailureEquitable, String>(
          this,
          Invocation.method(
            #execute,
            [movie],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.FailureEquitable, String>>);
}
