// Mocks generated by Mockito 5.0.8 from annotations
// in submission_one_menjadi_flutter_developer_expert_ditonton_app/test/presentation/pages/tv_show_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/common/request_state_enum.dart' as _i9;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/entities/tv_entities.dart' as _i10;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/entities/tv_detail.dart' as _i7;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/tv/get_all_tv_show_detail.dart' as _i2;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/tv/get_all_tv_show_recommendations.dart' as _i3;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/get_all_watchlist_status.dart' as _i4;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/remove_all_watchlist.dart' as _i6;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/domain/usecases/save_all_watchlist.dart' as _i5;
import 'package:submission_one_menjadi_flutter_developer_expert_ditonton_app/presentation/provider/tv/tv_show_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeGetTVShowDetail extends _i1.Fake implements _i2.GetAllTVShowDetail {}

class _FakeGetTVShowRecommendations extends _i1.Fake
    implements _i3.GetTVShowRecommendations {}

class _FakeGetWatchListTvShowStatus extends _i1.Fake
    implements _i4.GetAllWatchListTvShowStatus {}

class _FakeSaveWatchlistTvShow extends _i1.Fake implements _i5.SaveAllWatchlistTvShow {}

class _FakeRemoveWatchlistTvShow extends _i1.Fake implements _i6.RemoveAllWatchlistTvShow {}

class _FakeTVShowDetail extends _i1.Fake implements _i7.TVShowDetail {}

/// A class which mocks [TVDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class tVShowDetailNotifierMock extends _i1.Mock
    implements _i8.TVShowDetailNotifier {
  tVShowDetailNotifierMock() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAllTVShowDetail get getAllTVShowDetail =>
      (super.noSuchMethod(Invocation.getter(#getTVDetail),
          returnValue: _FakeGetTVShowDetail()) as _i2.GetAllTVShowDetail);
  @override
  _i3.GetTVShowRecommendations get getAllTVShowRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTVRecommendations),
              returnValue: _FakeGetTVShowRecommendations())
          as _i3.GetTVShowRecommendations);
  @override
  _i4.GetAllWatchListTvShowStatus get getWatchListTVStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
          returnValue: _FakeGetWatchListTvShowStatus()) as _i4.GetAllWatchListTvShowStatus);
  @override
  _i5.SaveAllWatchlistTvShow get saveWatchlistTV =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
          returnValue: _FakeSaveWatchlistTvShow()) as _i5.SaveAllWatchlistTvShow);
  @override
  _i6.RemoveAllWatchlistTvShow get removeWatchlistTV =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
          returnValue: _FakeRemoveWatchlistTvShow()) as _i6.RemoveAllWatchlistTvShow);
  @override
  _i7.TVShowDetail get tvDetail => (super.noSuchMethod(Invocation.getter(#tv),
      returnValue: _FakeTVShowDetail()) as _i7.TVShowDetail);
  @override
  _i9.EnumStateRequest get tvShowState =>
      (super.noSuchMethod(Invocation.getter(#tvState),
          returnValue: _i9.EnumStateRequest.DataEmpty) as _i9.EnumStateRequest);
  @override
  List<_i10.TVEntities> get tvShowRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvRecommendations),
          returnValue: <_i10.TVEntities>[]) as List<_i10.TVEntities>);
  @override
  _i9.EnumStateRequest get tvShowRecommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i9.EnumStateRequest.DataEmpty) as _i9.EnumStateRequest);
  @override
  String get mssg =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get tvShowAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  String get tvShowWatchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchTVDetail(int? idTv) =>
      (super.noSuchMethod(Invocation.method(#fetchTVDetail, [idTv]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlistTvShow(_i7.TVShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [tvShow]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i7.TVShowDetail? tvShow) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [tvShow]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> tvShowLoadWatchlistStatus(int? idTv) =>
      (super.noSuchMethod(Invocation.method(#loadWatchlistStatus, [idTv]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listenerTv) =>
      super.noSuchMethod(Invocation.method(#addListener, [listenerTv]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
