// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC09LONP19AakMaP9EK4xbVAeASWEHWMWw',
    appId: '1:168849300029:web:4e8f2e32b5b45834652854',
    messagingSenderId: '168849300029',
    projectId: 'submission-flutter-exper-6dfa8',
    authDomain: 'submission-flutter-exper-6dfa8.firebaseapp.com',
    storageBucket: 'submission-flutter-exper-6dfa8.appspot.com',
    measurementId: 'G-PBGFJ8Y8MN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGUXOh86YwahqJfsgm91HFkdFSgmVuDY0',
    appId: '1:168849300029:android:f5d94c10ad70652f652854',
    messagingSenderId: '168849300029',
    projectId: 'submission-flutter-exper-6dfa8',
    storageBucket: 'submission-flutter-exper-6dfa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH5imSgLUY727E7aUxY8MnigUn5UjadVU',
    appId: '1:168849300029:ios:ff62758803176b8d652854',
    messagingSenderId: '168849300029',
    projectId: 'submission-flutter-exper-6dfa8',
    storageBucket: 'submission-flutter-exper-6dfa8.appspot.com',
    iosClientId: '168849300029-ufl45vehm2e84v3fknoon80p4l0sbhmg.apps.googleusercontent.com',
    iosBundleId: 'com.james.submissiononemenjadiflutterdeveloperexpertditontonapp.submissionOneMenjadiFlutterDeveloperExpertDitontonApp',
  );
}
